/**
 * §5.6.7 seed data - `npm run db:seed -w apps/api`.
 *
 * Creates the admin, the demo owner/driver/guest, the emergency contact, the
 * two devices (CL-0001 real hardware, CL-0002 simulator), the two bikes, and
 * 14 days of synthetic history so the analytics screens are not empty at the
 * demo. Everything demo-related carries `isDemo = true` so `POST /demo/reset`
 * can clear it without touching real data.
 *
 * Device secrets are printed **once** to the console and written to a
 * gitignored `firmware/main-esp32/include/secrets.h`.
 *
 * Re-running is safe: users, devices and bikes are upserted by their natural
 * keys, and synthetic history is rebuilt from scratch each time.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import bcrypt from 'bcryptjs';
import { PrismaClient, type Prisma } from '@prisma/client';
import { DEFAULT_DEVICE_CONFIG, type IncidentType } from '@crashlink/contracts';
import { loadConfig } from '../src/config.js';
import {
  encryptSecret,
  generateApPassword,
  generateDeviceSecret,
  generatePairingCode,
} from '../src/lib/crypto.js';
import { severityScore } from '../src/lib/severity.js';

const prisma = new PrismaClient();
const config = loadConfig();

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');

/**
 * §5.6.7 marks these as "replace with a team member's real number for the live
 * demo" - the bike really does text them.
 */
const DEMO = {
  ownerPhone: '+94770000001',
  driverPhone: '+94770000002',
  contactPhone: '+94770000003',
} as const;

const DAY_MS = 86_400_000;

/** Colombo / Malabe, where the demo route runs. */
const COLOMBO = { lat: 6.9147, lon: 79.9729 };

const hashPassword = (password: string) => bcrypt.hash(password, 10);

const upsertUser = async (input: {
  role: 'ADMIN' | 'OWNER' | 'DRIVER' | 'GUEST';
  name: string;
  email: string;
  phone: string | null;
  password: string;
  isDemo: boolean;
}) => {
  const passwordHash = await hashPassword(input.password);

  return prisma.user.upsert({
    where: { email: input.email },
    create: {
      role: input.role,
      name: input.name,
      email: input.email,
      phoneE164: input.phone,
      passwordHash,
      isDemo: input.isDemo,
      consentAt: new Date(),
      settings: { create: {} },
    },
    update: {
      role: input.role,
      name: input.name,
      phoneE164: input.phone,
      passwordHash,
      isDemo: input.isDemo,
    },
  });
};

interface ProvisionedDevice {
  id: string;
  code: string;
  secret: string;
  pairingCode: string;
  cameraSecret: string;
  apPassword: string;
}

/**
 * Seeding a device regenerates its credentials, because the previous secret
 * only ever existed in the operator's terminal. Re-seeding therefore means
 * re-flashing the firmware.
 */
const seedDevice = async (code: string): Promise<ProvisionedDevice> => {
  const secret = generateDeviceSecret();
  const pairingCode = generatePairingCode();
  const cameraSecret = generateDeviceSecret();
  const apPassword = generateApPassword();

  const configJson = {
    ...DEFAULT_DEVICE_CONFIG,
    // CL-0002 is the simulator, so it may emit DEMO-sourced fixes (§5.3.3).
    demoMode: code === 'CL-0002',
    cameraSecret,
    apPassword,
  } as unknown as Prisma.InputJsonValue;

  const device = await prisma.device.upsert({
    where: { code },
    create: {
      code,
      secretEnc: encryptSecret(secret, config.DEVICE_SECRET_KEY),
      pairingCodeHash: await bcrypt.hash(pairingCode, 10),
      config: configJson,
    },
    update: {
      secretEnc: encryptSecret(secret, config.DEVICE_SECRET_KEY),
      pairingCodeHash: await bcrypt.hash(pairingCode, 10),
      config: configJson,
      revokedAt: null,
    },
  });

  return { id: device.id, code, secret, pairingCode, cameraSecret, apPassword };
};

const writeSecretsHeader = (devices: ProvisionedDevice[]): string => {
  const path = resolve(REPO_ROOT, 'firmware/main-esp32/include/secrets.h');
  const main = devices[0];
  if (!main) return path;

  const body = [
    '// Generated by `npm run db:seed -w apps/api`. GITIGNORED - never commit.',
    '// Re-running the seed regenerates these; re-flash the board afterwards.',
    '#pragma once',
    '',
    `#define CL_DEVICE_CODE   "${main.code}"`,
    `#define CL_DEVICE_SECRET "${main.secret}"`,
    `#define CL_CAMERA_SECRET "${main.cameraSecret}"`,
    `#define CL_AP_PASSWORD   "${main.apPassword}"`,
    `#define CL_API_HOST      "${config.DEVICE_BASE_URL}"`,
    '',
  ].join('\n');

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, 'utf8');
  return path;
};

/**
 * 14 days of synthetic history (§5.6.7): rentals, GPS traces and a spread of
 * INFO/SECURITY events plus three closed EMERGENCY incidents.
 *
 * All of it is `isDemo` and every incident type keeps its honest "Possible"
 * label - the seed does not manufacture a confirmed crash.
 */
const seedHistory = async (input: {
  ownerId: string;
  driverId: string;
  contactId: string;
  bikes: { id: string; label: string }[];
  ownerPhone: string;
  driverName: string;
  driverPhone: string;
  contactName: string;
  contactPhone: string;
}): Promise<void> => {
  const now = new Date();

  const bikeIds = input.bikes.map((bike) => bike.id);

  // Rebuild from scratch so re-seeding is a genuine reset, not an append.
  //
  // Open rentals (PENDING_SYNC / ACTIVE / ENDING_SYNC) are cleared too. Without
  // the device gateway nothing can ack a CLEAR_ASSIGNMENT, so a rental that
  // reaches ENDING_SYNC would otherwise pin the bike and the driver forever and
  // the next assignment would fail with DRIVER_BUSY (FR-RENT-02).
  await prisma.incident.deleteMany({ where: { ownerId: input.ownerId } });
  await prisma.locationSample.deleteMany({ where: { bikeId: { in: bikeIds } } });
  await prisma.ignitionEvent.deleteMany({ where: { bikeId: { in: bikeIds } } });
  await prisma.rental.deleteMany({ where: { ownerId: input.ownerId } });

  // Commands queued for the demo devices refer to rentals that no longer exist.
  await prisma.deviceCommand.deleteMany({
    where: { device: { bike: { id: { in: bikeIds } } } },
  });

  const infoTypes: IncidentType[] = ['POSSIBLE_POTHOLE', 'POSSIBLE_DANGEROUS_CORNERING'];
  const securityTypes: IncidentType[] = ['POSSIBLE_TOWING', 'POSSIBLE_TAMPERING', 'PARKED_BIKE_FALL'];
  const emergencyTypes: IncidentType[] = [
    'POSSIBLE_COLLISION',
    'POSSIBLE_LOW_SPEED_RIDER_DROP',
    'POSSIBLE_ROLLOVER',
  ];

  let assignmentVersion = 0;

  for (let dayAgo = 14; dayAgo >= 1; dayAgo -= 1) {
    const bike = input.bikes[dayAgo % input.bikes.length];
    if (!bike) continue;

    const startedAt = new Date(now.getTime() - dayAgo * DAY_MS + 9 * 3600_000);
    const endedAt = new Date(startedAt.getTime() + 75 * 60_000);
    assignmentVersion += 1;

    const rental = await prisma.rental.create({
      data: {
        bikeId: bike.id,
        driverId: input.driverId,
        ownerId: input.ownerId,
        emergencyContactId: input.contactId,
        ownerPhoneSnapshot: input.ownerPhone,
        driverNameSnapshot: input.driverName,
        driverPhoneSnapshot: input.driverPhone,
        contactNameSnapshot: input.contactName,
        contactPhoneSnapshot: input.contactPhone,
        state: 'ENDED',
        assignmentVersion,
        requestedAt: startedAt,
        deviceAckAt: startedAt,
        startedAt,
        endRequestedAt: endedAt,
        endedAt,
        distanceMeters: 3000 + ((dayAgo * 811) % 9000),
      },
    });

    // A short trace around Colombo so the map and distance charts have shape.
    const fixes = Array.from({ length: 12 }, (_, index) => ({
      bikeId: bike.id,
      rentalId: rental.id,
      fixAt: new Date(startedAt.getTime() + index * 5 * 60_000),
      lat: COLOMBO.lat + index * 0.0012 + dayAgo * 0.0004,
      lon: COLOMBO.lon + index * 0.0009 - dayAgo * 0.0003,
      speedKph: 12 + ((index * 7 + dayAgo) % 26),
      hdop: 1.1,
      satellites: 7,
      valid: true,
      source: 'GPS' as const,
    }));
    await prisma.locationSample.createMany({ data: fixes, skipDuplicates: true });

    // ~20 INFO/SECURITY events across the fortnight.
    const eventCount = dayAgo % 3 === 0 ? 2 : 1;
    for (let n = 0; n < eventCount; n += 1) {
      const isSecurity = (dayAgo + n) % 4 === 0;
      const pool = isSecurity ? securityTypes : infoTypes;
      const type = pool[(dayAgo + n) % pool.length];
      if (!type) continue;

      const occurredAt = new Date(startedAt.getTime() + (20 + n * 17) * 60_000);
      const evidence = isSecurity
        ? { simulated: true, note: 'Seeded demo history' }
        : { simulated: true, peakAccelerationG: 1.8 + n * 0.2, durationMs: 220 };

      await prisma.incident.create({
        data: {
          id: crypto.randomUUID(),
          bikeId: bike.id,
          rentalId: isSecurity ? null : rental.id,
          driverId: isSecurity ? null : input.driverId,
          ownerId: input.ownerId,
          type,
          category: isSecurity ? 'SECURITY' : 'INFO',
          state: isSecurity ? 'CLOSED' : 'INFO_RECORDED',
          occurredAt,
          receivedAt: occurredAt,
          timeSource: 'GPS',
          ignitionAtEvent: isSecurity ? 'OFF' : 'ON',
          preEventSpeedKph: isSecurity ? null : 24,
          locationKind: 'LIVE',
          lat: COLOMBO.lat + dayAgo * 0.0005,
          lon: COLOMBO.lon + dayAgo * 0.0004,
          fixAt: occurredAt,
          fixAgeSec: 3,
          locationSource: 'GPS',
          evidence: evidence as Prisma.InputJsonValue,
          decision: 'NOT_APPLICABLE',
          ownerAckAt: isSecurity ? occurredAt : null,
          closedAt: isSecurity ? occurredAt : null,
          isDemo: true,
        },
      });
    }
  }

  // Three closed EMERGENCY incidents, one per outcome, so the incident screens
  // show a real spread: SAFE by the rider, HELP, and a server TIMEOUT.
  const outcomes = [
    { decision: 'SAFE' as const, source: 'APP' as const, state: 'CLOSED' as const },
    { decision: 'HELP' as const, source: 'APP' as const, state: 'CLOSED' as const },
    { decision: 'TIMEOUT' as const, source: 'SERVER_TIMER' as const, state: 'CLOSED' as const },
  ];

  for (const [index, outcome] of outcomes.entries()) {
    const bike = input.bikes[index % input.bikes.length];
    if (!bike) continue;

    const type = emergencyTypes[index] ?? 'POSSIBLE_COLLISION';
    const occurredAt = new Date(now.getTime() - (index + 2) * DAY_MS);
    const questionSentAt = new Date(occurredAt.getTime() + 3000);
    const deadlineAt = new Date(questionSentAt.getTime() + config.RESPONSE_WINDOW_SEC * 1000);
    const decidedAt =
      outcome.decision === 'TIMEOUT' ? deadlineAt : new Date(questionSentAt.getTime() + 14_000);

    const evidence = {
      fallenDurationMs: 10_000,
      peakAccelerationG: 2.4 + index * 0.4,
      peakRotationDps: 160 + index * 40,
      maxTiltDeg: 84,
      simulated: true,
    };

    const incident = await prisma.incident.create({
      data: {
        id: crypto.randomUUID(),
        bikeId: bike.id,
        ownerId: input.ownerId,
        driverId: input.driverId,
        type,
        category: 'EMERGENCY',
        state: outcome.state,
        severityScore: severityScore({ ...evidence, preEventSpeedKph: 24 }),
        occurredAt,
        receivedAt: questionSentAt,
        timeSource: 'GPS',
        ignitionAtEvent: 'ON',
        preEventSpeedKph: 24,
        locationKind: 'LIVE',
        lat: COLOMBO.lat + index * 0.002,
        lon: COLOMBO.lon + index * 0.002,
        fixAt: occurredAt,
        fixAgeSec: 2,
        locationSource: 'GPS',
        evidence: evidence as Prisma.InputJsonValue,
        ownerPhoneSnapshot: input.ownerPhone,
        driverNameSnapshot: input.driverName,
        contactNameSnapshot: input.contactName,
        contactPhoneSnapshot: input.contactPhone,
        serverQuestion: true,
        questionSentAt,
        responseDeadlineAt: deadlineAt,
        decision: outcome.decision,
        decisionSource: outcome.source,
        decidedAt,
        photoStatus: 'NOT_REQUESTED',
        ownerAckAt: new Date(decidedAt.getTime() + 300_000),
        ownerNote: 'Seeded demo history',
        closedAt: new Date(decidedAt.getTime() + 300_000),
        isDemo: true,
      },
    });

    // §5.3.7: the owner SMS only ever reached AT_SUBMITTED - the modem returned
    // +CMGS. The seed does not claim delivery it cannot prove.
    await prisma.notification.create({
      data: {
        incidentId: incident.id,
        kind: 'OWNER_SMS',
        state: 'AT_SUBMITTED',
        recipientMasked: `+94•••••${input.ownerPhone.slice(-4)}`,
        attempts: {
          create: { attemptNo: 1, state: 'AT_SUBMITTED', detail: '+CMGS: 23', deviceTime: questionSentAt },
        },
      },
    });

    if (outcome.decision !== 'SAFE') {
      await prisma.notification.create({
        data: {
          incidentId: incident.id,
          kind: 'CONTACT_SMS',
          state: 'AT_SUBMITTED',
          recipientMasked: `+94•••••${input.contactPhone.slice(-4)}`,
          attempts: {
            create: { attemptNo: 1, state: 'AT_SUBMITTED', detail: '+CMGS: 24', deviceTime: decidedAt },
          },
        },
      });
    }

    if (outcome.decision === 'SAFE' || outcome.decision === 'HELP') {
      await prisma.driverResponse.create({
        data: {
          incidentId: incident.id,
          choice: outcome.decision,
          source: 'APP',
          responderUserId: input.driverId,
          idempotencyKey: crypto.randomUUID(),
          serverReceivedAt: decidedAt,
          accepted: true,
        },
      });
    }
  }
};

const main = async (): Promise<void> => {
  const adminPassword = config.ADMIN_SEED_PASSWORD;
  if (!adminPassword) {
    throw new Error('ADMIN_SEED_PASSWORD must be set before seeding (Appendix B).');
  }

  const admin = await upsertUser({
    role: 'ADMIN',
    name: 'CrashLink Admin',
    email: 'admin@crashlink.lk',
    phone: null,
    password: adminPassword,
    isDemo: false,
  });

  // Demo logins are fixed and printed below: M11 removed password reset, so the
  // team needs to be able to sign in without one.
  const owner = await upsertUser({
    role: 'OWNER',
    name: 'Nimal Perera',
    email: 'owner@demo.lk',
    phone: DEMO.ownerPhone,
    password: 'demo1234',
    isDemo: true,
  });

  const driver = await upsertUser({
    role: 'DRIVER',
    name: 'Ravi Kumar',
    email: 'ravi@demo.lk',
    phone: DEMO.driverPhone,
    password: 'demo1234',
    isDemo: true,
  });

  const guest = await upsertUser({
    role: 'GUEST',
    name: 'Judge (read-only)',
    email: 'judge@demo.lk',
    phone: null,
    password: 'demo1234',
    isDemo: true,
  });

  // FR-DRV-01: exactly one current contact per driver (§5.6.3).
  await prisma.emergencyContact.updateMany({
    where: { driverId: driver.id, isCurrent: true },
    data: { isCurrent: false },
  });
  const contact = await prisma.emergencyContact.create({
    data: {
      driverId: driver.id,
      name: 'Kamala',
      phoneE164: DEMO.contactPhone,
      relationship: 'Mother',
      isCurrent: true,
    },
  });

  const deviceOne = await seedDevice('CL-0001');
  const deviceTwo = await seedDevice('CL-0002');

  const bikeOne = await prisma.bike.upsert({
    where: { deviceId: deviceOne.id },
    create: {
      ownerId: owner.id,
      deviceId: deviceOne.id,
      label: 'Scooter 1',
      plateNo: 'WP BCD-1234',
      status: 'AVAILABLE',
      isDemo: true,
    },
    update: { ownerId: owner.id, label: 'Scooter 1', status: 'AVAILABLE' },
  });

  const bikeTwo = await prisma.bike.upsert({
    where: { deviceId: deviceTwo.id },
    create: {
      ownerId: owner.id,
      deviceId: deviceTwo.id,
      label: 'Scooter 2',
      plateNo: 'WP BCD-5678',
      status: 'AVAILABLE',
      isDemo: true,
    },
    update: { ownerId: owner.id, label: 'Scooter 2', status: 'AVAILABLE' },
  });

  await seedHistory({
    ownerId: owner.id,
    driverId: driver.id,
    contactId: contact.id,
    bikes: [
      { id: bikeOne.id, label: bikeOne.label },
      { id: bikeTwo.id, label: bikeTwo.label },
    ],
    ownerPhone: DEMO.ownerPhone,
    driverName: driver.name,
    driverPhone: DEMO.driverPhone,
    contactName: contact.name,
    contactPhone: contact.phoneE164,
  });

  const secretsPath = writeSecretsHeader([deviceOne, deviceTwo]);

  /* eslint-disable no-console */
  console.log('');
  console.log('  CrashLink seed complete');
  console.log('  ----------------------------------------------------------------');
  console.log(`  admin    ${admin.email} / ADMIN_SEED_PASSWORD`);
  console.log(`  owner    ${owner.email} / demo1234   (Nimal Perera)`);
  console.log(`  driver   ${driver.email} / demo1234   (Ravi Kumar)`);
  console.log(`  guest    ${guest.email} / demo1234   (read-only)`);
  console.log('');
  console.log('  Device secrets - shown ONCE, not recoverable:');
  for (const device of [deviceOne, deviceTwo]) {
    console.log(`    ${device.code}  secret=${device.secret}`);
    console.log(`    ${device.code}  pairingCode=${device.pairingCode}  apPassword=${device.apPassword}`);
  }
  console.log('');
  console.log(`  Wrote ${secretsPath} (gitignored).`);
  console.log('');
  console.log('  NOTE (§5.6.7): replace the demo phone numbers with real team');
  console.log('  numbers before the live demo - the bike actually texts them.');
  console.log('');
  /* eslint-enable no-console */
};

main()
  .catch((error: unknown) => {
    // eslint-disable-next-line no-console
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
